config/routes.rb
Rails.application.routes.draw do
    devise_for :marchants
    devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
    end
    root 'dashboard#index'
    resources :transactions
    post '/verify_payment' => 'transactions#verify_payment'
    resources :dashboard, only: [:index]
 	resources :marchant_users
  	resources :users
  	resources :theaters do 
        resources :movies do 
            get :book_now
        end
    end
    resources :timings
    resources :movies, only: [:show] do
        get :add_picture
        get :info
        resources :pictures
    end
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marchant.rb
class Marchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :theaters , dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
	belongs_to :theater	
	has_many :pictures ,dependent: :destroy
	has_many :timings
	has_many :transactions
	accepts_nested_attributes_for :timings,:allow_destroy => true
	accepts_nested_attributes_for :pictures,:allow_destroy => true
end

app/models/picture.rb
class Picture < ApplicationRecord
	mount_uploader :image, AvatarUploader
	belongs_to :movie
def all_picture
		"#{self.image}"
	end
end

app/models/theater.rb
class Theater < ApplicationRecord
	belongs_to :marchant
	has_many :movies, dependent: :destroy
	has_many :transactions
	def fetch_time movie
		self.movies.find_by(name: movie.name).timings
	end
end

app/models/timing.rb
class Timing < ApplicationRecord
  belongs_to :movie
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
	belongs_to :movie
	belongs_to :theater
	belongs_to :timing
end

app/models/user.rb
class User < ApplicationRecord
     devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :transactions
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
   def index
    	@movies = Movie.all.to_a.uniq { |item| item.name }
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user!, only: [:book_now]
  	def index
 	 	@movies = Movie.all
	end
	def new
		@theater = Theater.find(params[:theater_id])
		@movie = @theater.movies.build
	end
	def show		
		@movie = Movie.find_by(id: params[:id])		
		@theaters = Theater.joins(:movies).where('movies.name LIKE ?', @movie.name).uniq
	end
	def create
		@theater = Theater.find(params[:theater_id])
		@movie = @theater.movies.new(movies_params)
		@movie.name = @movie.name.downcase.strip
 		@movie.save
  		redirect_to theater_path(@theater)
	end
	def edit
		@theater = Theater.find(params[:theater_id])
		@movie = Movie.find(params[:id])
	end
	def update
		@theater = Theater.find(params[:theater_id])
		@movies = Movie.find(params[:id])
		if @movies.update(movies_params)
     		redirect_to theater_path(@theater)
     	else
     		render 'edit'
     	end
  	end
 	def book_now
  		 @movie = Movie.find(params[:movie_id])
 		 @theater = Theater.find(params[:theater_id])
  		 @timing = Timing.last
  		 @transaction = Transaction.new
 	end
  	def info
  		@movie = Movie.find_by(id: params[:movie_id])
  	end
private
	def movies_params
 	 	params.require(:movie).permit( :name, :description, :price, :start_date,:end_date, :status,
 	 								timings_attributes: [:id,:start_time,:_destroy],
 	 								pictures_attributes: [:id,:image,:_destroy]) 	 
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :authenticate_marchant!
	def new
		@movie = Movie.find(params[:movie_id])
		@picture = Picture.new
		@pictures = @movie.pictures 
	end
	def create
		@movie = Movie.find(params[:movie_id])
		@picture = 	@movie.pictures.create(picture_params)
		@picture.save
		redirect_to new_movie_picture_path
	end
	def show
		@pic_delete = Picture.find(params[:id])
		@pic_delete.destroy
		redirect_to movie_info_path
	end
	private
	def picture_params
		params.require(:picture).permit(:image )
	end
end


app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
	before_action :authenticate_marchant!
	def new
		@theater = current_marchant.theaters.new
	end
	def create		
		@theater = current_marchant.theaters.new(theaters_params)
 		@theater.save
  		redirect_to marchant_users_path
	end
	def show
		@theater = current_marchant.theaters.find(params[:id])
	end
	def edit
		@theater_edit = current_marchant.theaters.find(params[:id])
	end
	def update 		
 		@theater_u = current_marchant.theaters.find(params[:id])
  		if @theater_u.update(theaters_params)
   			 redirect_to marchant_users_path
 		 else
    		render 'edit'
  		end
	end
	def index
		@theaters =  current_marchant.theaters
	end
private
	def theaters_params
 	 params.require(:theater).permit(:name, :contact_no, :address)
	end
end

app/controllers/timings_controller.rb
class TimingsController < ApplicationController
	def new
		@timing = Timings.all
	end

	def index
		movie_id = params[:movie]
		theater_id =  params[:theater]
		@movie = Movie.find(movie_id)
		@theater = Theater.find(theater_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/marchant_users_helper.rb
module MarchantUsersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/paytm_helper.rb
module PaytmHelper
    include Paytm::EncryptionNewPG
	 def generate_checksum
	    new_pg_checksum(@paramList, @paytm_keys['PAYTM_MERCHANT_KEY']).gsub("\n",'')
	end

	def verify_checksum
	    new_pg_verify_checksum(@paytmparams, @checksum_hash, @paytm_keys['PAYTM_MERCHANT_KEY'])
	end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="container">
   <div class="row" >
   	<% @movies.each do |movie|%>
      <div class="col-md-4">
         <figure class="card card-product">
            <div class="img-wrap">
            <%if movie.pictures.present? %>
               <img src="<%= movie.pictures.first.image.url%>">
            <%else%>
                           <img src="/assets/image1.jpg">

            <%end%>
            </div>
            <figcaption class="info-wrap">
               <h2 class=""><%= movie.name %></h2>
               <h4 class=""><%= movie.description %></h4>
               <h4 class=""><%= movie.price %></h4>
               
               <div class="rating-wrap">
                  <div class="label-rating">132 reviews</div>
                  <div class="label-rating">154 book </div>
               </div>
            </figcaption>
            <div class="bottom-wrap">
               <%= link_to "Book Now", movie_path(movie.id), class: "btn btn-sm btn-primary float-right" %>
               <div class="price-wrap h5">
               </div>
            </div>
         </figure>
      </div>
      <% end %>
   </div>
</div>




app/views/movies/_form.html.erb
<%= link_to 'Back',theater_path(@theater), class: "btn btn-primary" %>
<div class="container h-100">
    <div class="row">
        <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-12 col-xs-12">  
            <div class="card_height">
                
                    <h1><%= @theater.name %></h1>
                <%= nested_form_for [ @theater, @movie ] do |form| %>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="group" > Name</label>
                                    <td><%= form.text_field :name,class: "input",placeholder: "movie Name" %><td>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="group"> price</label>
                                    <td><%= form.number_field :price,class: "input" %><td>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="group">start_date</label>
                                    <td><%= form.date_field :start_date,class: "input" %><td>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="group">end_date</label>
                                    <td><%= form.date_field :end_date,class: "input" %><td>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="form-group">
                                    <label class="group" >description</label>
                                    <td><%= form.text_field :description,class: "input",placeholder: "description" %><td>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                                <div class="form-group">
                                    <label class="group">Active</label>
                                    <td><%= form.check_box :status,class: "input" %><td>
                                </div>
                            </div>
                            <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12" >
                                <div class="nested-fields">
                            <%= form.fields_for :timings do |form| %>
                                <label class="group">start_time</label>
                                <td><%= form.time_field :start_time,class: "input" %></td>
                                <%= form.link_to_remove "Remove this task" %>
                            <% end %>
                            <p><%= form.link_to_add "Add timing", :timings,class: "btn btn-info" %></p>
                                </div>
                            </div>
                            <div class="row">
                            <div class= "col-lg-12 col-md-12 col-sm-12 col-xs-12" >
                            <div class= "nested-fields" >
                            <%= form.fields_for :pictures do |form| %>
                                <label class="group">image</label>
                                  
                                  <td><%= form.file_field :image %></td>
                                  <%= form.link_to_remove "Remove this task",class: "input" %>
                            <% end %>
                              <p><%= form.link_to_add "Add Pictures", :pictures, class: "btn btn-info" %></p>
                            </div>
                            </div>
                        </div>
                             <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                            <td> <%= form.submit "save", class: "btn btn-primary" %></td>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/movies/book_now.html.erb
<div><%= link_to 'back',dashboard_index_path,class: 'btn btn-success' %></div>
<div class="container h-100">
    <div class="row">
            <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-12 col-xs-12">  
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">

                    <h4>Theater name:</h4>
                        <h3><%= @theater.name %></h3>
                    <h4>Movie name:</h4>
                        <h3><%= @movie.name %></h3>
                        <h4>movie price:</h4>
                        <h3><%= @movie.price%></h3>
                    <h4>StartTime</h4>
                        <h4><%= @timing.start_time %></h4>
                    <%= form_with scope: :transaction, url: transactions_path, local: true do |form| %>
                        <table>
                            <%= form.hidden_field :theater_id,value: @theater.id %>
                            <%= form.hidden_field :movie_id,value: @movie.id %>
                            <%= form.hidden_field :timing_id,value: @timing.id %>
                            <tr>
                                <td><%= form.label :quantity %></td>
                                 <td><%= form.number_field :quantity,min:1, class: "size"%></td> 
                            </tr>
                            <tr>
                                <td><%= form.label :total_amount %></td>

            
                                <td><%= form.text_field :total_amount, class: "size" %></td>
                            </tr>
                            <tr>
                                <td> <%= form.submit %></td>
                            </tr>        
                        </table>
                    <% end %>
                       <div><%= link_to 'select your seat',timings_path(movie: @movie.id , theater: @theater.id),class: 'btn btn-success' %></div>

                    </div>
                </div>
            </div>
        </div>
    </div>

<script type="text/javascript">
    
    $(document).ready(function() {
    /* Assign actions */
    $('#transaction_quantity').change( function() {
      updateQuantity(this);
    });
     
     
    /* Update quantity */
    function updateQuantity(quantityInput)
    {
        console.log(quantityInput)
      /* Calculate line price */
      var productRow = $(quantityInput).parent().parent();
      var price = <%= @movie.price%>;
      var quantity = $(quantityInput).val();
      var linePrice = price * quantity;
       
       $('#transaction_total_amount').val(linePrice)
      /* Update line price display and recalc cart totals */
    }
    });
     

</script>




app/views/movies/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="content-container">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
 

app/views/movies/index.html.erb
<div class="container h-100">
    <div class="row">
            <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-12 col-xs-12">  
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
              <tr>
                <th>name</th>
                <th>description</th>
                <th>price</th>
                <th>theater_id</th>
              </tr>
               <% @movies.each do |movie| %>
              <tr>
                  <td><%= movie.name %></td>
                  <td><%= movie.description %></td>
                  <td><%= movie.price%></td>
                  <td><%= movie.theater_id%></td>
                  <td><%= link_to 'Show', movie_path(movie) %></td>
                  <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
              </tr>
              <% end %>
            </table>
            <%= link_to 'new page ', new_movie_path %>
             </div>
            </div>
          </div>
    </div>
</div>


app/views/movies/info.html.erb
<%= link_to 'Back',theater_path(@movie.theater), class: "btn btn-primary" %>
<div class="container h-100">
    <div class="row">
        <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-12 col-xs-12">  
            <div class="card_height">
				
           		<h2>movie name:</h2>
				<p><%= @movie.name %></p>
				<h2>theater name</h2>
				<p><%= @movie.theater.name %></p>
				<div class="theater_view">
					<% if @movie.timings.present? %>
						<% @movie.timings.each do |t| %>
						<h2>timing</h2>
							<span><%= t.start_time.strftime("%H:%M %p" )%></span>
						<% end %>
					<% end %>
				</div>
				<div>
					<% if @movie.pictures.present? %>
					<div class="row">
						<% @movie.pictures.each do |pic| %>
							<div class= "col-md-3">
								<h2>images</h2>
							<div><%= image_tag(pic.image.url, height: "200px", width: "200px")%></div>
							<span><%= link_to 'Delete' , movie_picture_path(@movie,pic) , class: "btn btn-success" %></span>
							</div>
					
					<% end %>
				</div>
					<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/movies/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="content-container">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>					


app/views/movies/show.html.erb
<div><%= link_to 'back',dashboard_index_path,class: 'btn btn-success' %></div>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="content-container">
      	<%if @movie.pictures.present? %>
      			<% @movie.pictures.each do |movie|%>
               <img src="<%= movie.image.url%>">
               <%end%>
            <%else%>
                           <img src="/assets/image1.jpg">

            <%end%>
		<h1><%= @movie.name %></h1>
		<% @theaters.each do |t| %>
		<div class="theater_view">
			<h4><%= t.name %></h4>
			<% t.fetch_time(@movie).each do |time| %>
				<span><%= time.start_time.strftime("%H:%M %p")%></span> 
			<% end %>
		</div>
		<div class="book_now">
			<%= link_to 'Book Now', theater_movie_book_now_path(t,@movie), class: "btn btn-success" %>
		</div>
		<% end %>
      </div>
    </div>
    </div>
</div>


app/views/timings/new.html.erb
<h1>hello</h1>