config/routes.rb
Rails.application.routes.draw do
    devise_for :marchants
    devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
    end
    root 'dashboard#index'
    resources :transactions
    post '/verify_payment' => 'transactions#verify_payment'
    resources :dashboard, only: [:index]
 	resources :marchant_users
  	resources :users
  	resources :theaters do 
        resources :movies do 
            get :book_now
        end
    end
    resources :timings
    resources :movies, only: [:show] do
        get :add_picture
        get :info
        resources :pictures
    end
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marchant.rb
class Marchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :theaters , dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
	belongs_to :theater	
	has_many :pictures ,dependent: :destroy
	has_many :timings
	has_many :transactions
	accepts_nested_attributes_for :timings,:allow_destroy => true
	accepts_nested_attributes_for :pictures,:allow_destroy => true
end

app/models/picture.rb
class Picture < ApplicationRecord
	mount_uploader :image, AvatarUploader
	belongs_to :movie
def all_picture
		"#{self.image}"
	end
end

app/models/theater.rb
class Theater < ApplicationRecord
	belongs_to :marchant
	has_many :movies, dependent: :destroy
	has_many :transactions
	def fetch_time movie
		self.movies.find_by(name: movie.name).timings
	end
end

app/models/timing.rb
class Timing < ApplicationRecord
  belongs_to :movie
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
	belongs_to :movie
	belongs_to :theater
	belongs_to :timing
end

app/models/user.rb
class User < ApplicationRecord
     devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   

	def after_sign_in_path_for(resource)		
        if current_marchant
            marchant_users_path
        else
        	root_path
        end 
     end      
    before_action :configure_permitted_parameters, if: :devise_controller?
protected
	def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_no])
	end
end 

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
   def index
    	@movies = Movie.all.to_a.uniq { |item| item.name }
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user!, only: [:book_now]
  	def index
 	 	@movies = Movie.all
	end
	def new
		@theater = Theater.find(params[:theater_id])
		@movie = @theater.movies.build
	end
	def show		
		@movie = Movie.find_by(id: params[:id])		
		@theaters = Theater.joins(:movies).where('movies.name LIKE ?', @movie.name).uniq
	end
	def create
		@theater = Theater.find(params[:theater_id])
		@movie = @theater.movies.new(movies_params)
		@movie.name = @movie.name.downcase.strip
 		@movie.save
  		redirect_to theater_path(@theater)
	end
	def edit
		@theater = Theater.find(params[:theater_id])
		@movie = Movie.find(params[:id])
	end
	def update
		@theater = Theater.find(params[:theater_id])
		@movies = Movie.find(params[:id])
		if @movies.update(movies_params)
     		redirect_to theater_path(@theater)
     	else
     		render 'edit'
     	end
  	end
 	def book_now
  		 @movie = Movie.find(params[:movie_id])
 		 @theater = Theater.find(params[:theater_id])
  		 @timing = Timing.last
  		 @transaction = Transaction.new
 	end
  	def info
  		@movie = Movie.find_by(id: params[:movie_id])
  	end
private
	def movies_params
 	 	params.require(:movie).permit( :name, :description, :price, :start_date,:end_date, :status,
 	 								timings_attributes: [:id,:start_time,:_destroy],
 	 								pictures_attributes: [:id,:image,:_destroy]) 	 
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :authenticate_marchant!
	def new
		@movie = Movie.find(params[:movie_id])
		@picture = Picture.new
		@pictures = @movie.pictures 
	end
	def create
		@movie = Movie.find(params[:movie_id])
		@picture = 	@movie.pictures.create(picture_params)
		@picture.save
		redirect_to new_movie_picture_path
	end
	def show
		@pic_delete = Picture.find(params[:id])
		@pic_delete.destroy
		redirect_to movie_info_path
	end
	private
	def picture_params
		params.require(:picture).permit(:image )
	end
end


app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
	before_action :authenticate_marchant!
	def new
		@theater = current_marchant.theaters.new
	end
	def create		
		@theater = current_marchant.theaters.new(theaters_params)
 		@theater.save
  		redirect_to marchant_users_path
	end
	def show
		@theater = current_marchant.theaters.find(params[:id])
	end
	def edit
		@theater_edit = current_marchant.theaters.find(params[:id])
	end
	def update 		
 		@theater_u = current_marchant.theaters.find(params[:id])
  		if @theater_u.update(theaters_params)
   			 redirect_to marchant_users_path
 		 else
    		render 'edit'
  		end
	end
	def index
		@theaters =  current_marchant.theaters
	end
private
	def theaters_params
 	 params.require(:theater).permit(:name, :contact_no, :address)
	end
end

app/controllers/timings_controller.rb
class TimingsController < ApplicationController
	def new
		@timing = Timings.all
	end

	def index
		movie_id = params[:movie]
		theater_id =  params[:theater]
		@movie = Movie.find(movie_id)
		@theater = Theater.find(theater_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/marchant_users_helper.rb
module MarchantUsersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/paytm_helper.rb
module PaytmHelper
    include Paytm::EncryptionNewPG
	 def generate_checksum
	    new_pg_checksum(@paramList, @paytm_keys['PAYTM_MERCHANT_KEY']).gsub("\n",'')
	end

	def verify_checksum
	    new_pg_verify_checksum(@paytmparams, @checksum_hash, @paytm_keys['PAYTM_MERCHANT_KEY'])
	end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pictures/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="content-container">
                <p><%= @movie.name%>
                    <%= @movie.description %>
                    <%= @movie.price %>
                    <%= @movie.start_date%>
                    <%= @movie.end_date %>
                    <%= @movie.status%>
                </p><br><br>
                <div class="row"> 
                    <% @pictures.each do|picture|%>
                        <div class="col-md-4">
                            <%= image_tag(picture.image.url, height: 200, width: 150)%>
                        </div>
                    <% end %>
                </div>
                <%= form_for [@movie , @picture] do |form| %><br><br>
                    <p><%= form.label :upload_image %>
                    <%= form.file_field :image %></p>
                    <p><%= form.submit "Upload", class: "btn btn-primary" %></p>
                  <% end %>
            </div>
        </div>
    </div>
</div>


app/views/theaters/_form.html.erb
<%= link_to 'back' ,marchant_users_path,class: "btn btn-primary" %>
<div class="container h-100">
    <div class="row">
        <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-12 col-xs-12"> 
        <div id="banner"> 
            <div class="user_card">
       
              <%= form_with scope: :theater, url: theaters_path, local: true do |form| %>
                            <div class="form-group">
                                    <label class="group" > Name</label>
                                    <td><%= form.text_field :name,class: "input" %></td>
                                </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label class="group"> contact no</label>
                                    <td><%= form.text_field :contact_no,class: "input" %></td>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label class="group">address</label>
                                    <td><%= form.text_field :address,class: "input" %></td>
                                </div>
                            </div>
                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                            <td><%= form.submit "Save", class: "btn btn-primary" %></td>
                        </div>
                <% end %>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/theaters/edit.html.erb
<p><%= link_to "Back ", marchant_users_path  , class: "btn btn-primary"%></p>
<div class="container h-100">
    <div class="row">
        <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-12 col-xs-12">  
            <div id="banner">
               <!--  <div id="cloud-scroll"> -->
            <div class="user_card">
                <%= form_for(@theater_edit) do |form| %>
                    <h2> Name</h2>
                        <td><%= form.text_field :name %></td>
                    <h2>contact no</h2>
                        <td><%= form.text_field :contact_no %><td>
                    <h2>address</h2>
                        <td><%= form.text_field :address %><td>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                    <td><%= form.submit "Save", class: "btn btn-primary" %></td>
                    </div>
                <% end %> 
            </div>
        <!--  </div> -->
    </div>
</div>      
</div>
</div>
<style>
     
  
</style>

app/views/theaters/new.html.erb
<%= render 'form'%>

app/views/theaters/show.html.erb
<p><%= link_to "Back ", marchant_users_path  , class: "btn btn-primary"%></p>
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<div class="content-container">
				<h1><%=@theater.name%></h1>
					<table class="table">
					 	 <thead class="thead-dark">
					   		 <tr>
					      		<th scope="col">name</th>
					      		<th scope="col">description</th>
	      						<th scope="col">price</th>
	      						<th scope="col">start date </th>
	      						<th scope="col">end date </th>
	      						<th scope="col">active</th>
	      						<th colspan="2">Actions</th>
					    	</tr>
					  </thead>
					  <tbody>
					  	<% @theater.movies.each do |movie| %>  
						    <tr>
						      <td><%= movie.name%></td>
						      <td><%= movie.description %></td>
						      <td><%= movie.price %></td>
						      <td><%= movie.start_date%></td>
						      <td><%= movie.end_date %></td>
						      <td><%= movie.status%></td>
						      <td><%= link_to "edit" , edit_theater_movie_path(@theater, movie) %></td>
						      <td><%= link_to " show  " , movie_info_path(movie) , class: "btn btn-success"%></td>
						    </tr>
						<% end %>
					  </tbody>
					</table>
				<p><%= link_to " add movie " ,new_theater_movie_path(@theater) , class: "btn btn-success"%></p>
				
			</div>
		</div>
	</div>
</div>					


