config/routes.rb
Rails.application.routes.draw do
    devise_for :marchants
    devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
    end
    root 'dashboard#index'
    resources :transactions
    post '/verify_payment' => 'transactions#verify_payment'
    resources :dashboard, only: [:index]
 	resources :marchant_users
  	resources :users
  	resources :theaters do 
        resources :movies do 
            get :book_now
        end
    end
    resources :timings
    resources :movies, only: [:show] do
        get :add_picture
        get :info
        resources :pictures
    end
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marchant.rb
class Marchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :theaters , dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
	belongs_to :theater	
	has_many :pictures ,dependent: :destroy
	has_many :timings
	has_many :transactions
	accepts_nested_attributes_for :timings,:allow_destroy => true
	accepts_nested_attributes_for :pictures,:allow_destroy => true
end

app/models/picture.rb
class Picture < ApplicationRecord
	mount_uploader :image, AvatarUploader
	belongs_to :movie
def all_picture
		"#{self.image}"
	end
end

app/models/theater.rb
class Theater < ApplicationRecord
	belongs_to :marchant
	has_many :movies, dependent: :destroy
	has_many :transactions
	def fetch_time movie
		self.movies.find_by(name: movie.name).timings
	end
end

app/models/timing.rb
class Timing < ApplicationRecord
  belongs_to :movie
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
	belongs_to :movie
	belongs_to :theater
	belongs_to :timing
end

app/models/user.rb
class User < ApplicationRecord
     devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :transactions
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user!, only: [:book_now]
  	def index
 	 	@movies = Movie.all
	end
	def new
		@theater = Theater.find(params[:theater_id])
		@movie = @theater.movies.build
	end
	def show		
		@movie = Movie.find_by(id: params[:id])		
		@theaters = Theater.joins(:movies).where('movies.name LIKE ?', @movie.name).uniq
	end
	def create
		@theater = Theater.find(params[:theater_id])
		@movie = @theater.movies.new(movies_params)
		@movie.name = @movie.name.downcase.strip
 		@movie.save
  		redirect_to theater_path(@theater)
	end
	def edit
		@theater = Theater.find(params[:theater_id])
		@movie = Movie.find(params[:id])
	end
	def update
		@theater = Theater.find(params[:theater_id])
		@movies = Movie.find(params[:id])
		if @movies.update(movies_params)
     		redirect_to theater_path(@theater)
     	else
     		render 'edit'
     	end
  	end
 	def book_now
  		 @movie = Movie.find(params[:movie_id])
 		 @theater = Theater.find(params[:theater_id])
  		 @timing = Timing.last
  		 @transaction = Transaction.new
 	end
  	def info
  		@movie = Movie.find_by(id: params[:movie_id])
  	end
private
	def movies_params
 	 	params.require(:movie).permit( :name, :description, :price, :start_date,:end_date, :status,
 	 								timings_attributes: [:id,:start_time,:_destroy],
 	 								pictures_attributes: [:id,:image,:_destroy]) 	 
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :authenticate_marchant!
	def new
		@movie = Movie.find(params[:movie_id])
		@picture = Picture.new
		@pictures = @movie.pictures 
	end
	def create
		@movie = Movie.find(params[:movie_id])
		@picture = 	@movie.pictures.create(picture_params)
		@picture.save
		redirect_to new_movie_picture_path
	end
	def show
		@pic_delete = Picture.find(params[:id])
		@pic_delete.destroy
		redirect_to movie_info_path
	end
	private
	def picture_params
		params.require(:picture).permit(:image )
	end
end


app/controllers/timings_controller.rb
class TimingsController < ApplicationController
	def new
		@timing = Timings.all
	end

	def index
		movie_id = params[:movie]
		theater_id =  params[:theater]
		@movie = Movie.find(movie_id)
		@theater = Theater.find(theater_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/marchant_users_helper.rb
module MarchantUsersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/paytm_helper.rb
module PaytmHelper
    include Paytm::EncryptionNewPG
	 def generate_checksum
	    new_pg_checksum(@paramList, @paytm_keys['PAYTM_MERCHANT_KEY']).gsub("\n",'')
	end

	def verify_checksum
	    new_pg_verify_checksum(@paytmparams, @checksum_hash, @paytm_keys['PAYTM_MERCHANT_KEY'])
	end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<article class="bg-secondary mb-3">
   <footer class="text-center card-body">
      <span>Google</span>
      <span>About Google</span>
      <span>Privacy</span>
      <span>Terms</span>
   </footer>
</article>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="menu">
   <a class="navbar-brand" href="/">BookMyShow</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
   </button>
       <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
         <ul class="navbar-nav ml-auto">
              <li class="nav-item">
        <% if user_signed_in? || marchant_signed_in? %>
            <% if current_user %>
                <%= link_to 'Logout',destroy_user_session_path, class: "nav-item nav-link active" %>
            <% else %>
                <%= link_to 'Logout',destroy_marchant_session_path, class: "nav-item nav-link active" %>
            <% end %>        
              <li><%= link_to "theater_list ", marchant_users_path  , class: "nav-item nav-link active"%></li>
        <% else %> 
              <li class="nav-item">   
            <%=link_to 'Login', new_user_session_path, class: "nav-item nav-link active" %>
          </li>
          <li class="nav-item">
            <%=link_to 'BussinessLogin',  new_marchant_session_path, class: "nav-item nav-link active" %> 
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieBooking</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>